#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CalcaliciousAndroid.Resource", IsApplication=true)]

namespace CalcaliciousAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040013
			public const int button0 = 2130968595;
			
			// aapt resource value: 0x7f040003
			public const int button1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int button2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int button3 = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int button4 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int button5 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int button6 = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int button7 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int button8 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int button9 = 2130968591;
			
			// aapt resource value: 0x7f040006
			public const int buttonAdd = 2130968582;
			
			// aapt resource value: 0x7f040012
			public const int buttonDecimalPoint = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int buttonDivide = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int buttonEquals = 2130968596;
			
			// aapt resource value: 0x7f040010
			public const int buttonMultiply = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int buttonSubtract = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int linearLayout0 = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int linearLayout1 = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int linearLayout2 = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int linearLayout3 = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int linearLayout4 = 2130968593;
			
			// aapt resource value: 0x7f040001
			public const int textExpression = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
